### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by osm-dev** [rafaelstz/dev-alias#11]
Getting Segmentation fault when trying to run n98 command

// linux-version
PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
NAME="Debian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="http://bugs.debian.org/"

**Comment by rafaelstz** [comment]
[PHP 5.4 and APC causing Segmentation fault](http://www.activo.com/php-5-4-and-apc-causing-segmentation-fault-with-magento/), these guys decided, so you can solve your problem:

https://github.com/netz98/n98-magerun/issues/224
